#
# Copyright (C) 2023 kulupu.io development team (turretkeeper@kulupu.io)
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for Ruvchain Network
LUCI_DEPENDS:=+ruvchain
LUCI_PKGARCH:=all
PKG_VERSION:=1.0.0
PKG_MAINTAINER:= ruvcoindev <admin@ruvcha.in>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
